import { CompiledSliceV1, ProjectManifestV1, SliceDefinitionV1, SliceEdgeV1, assertSliceId, normalizeBrainSharePath } from "@brainshare/protocol";
import { parseMarkdown } from "@brainshare/markdown";

const ENCODING = "0123456789ABCDEFGHJKMNPQRSTVWXYZ";
export function createUlid(now=Date.now()): string {
  let time=now, out="";
  for(let i=0;i<10;i++){out=ENCODING[time%32]+out;time=Math.floor(time/32)}
  const bytes=new Uint8Array(10);
  if(globalThis.crypto?.getRandomValues) globalThis.crypto.getRandomValues(bytes); else for(let i=0;i<bytes.length;i++) bytes[i]=Math.floor(Math.random()*256);
  let bits=0, value=0; for(const b of bytes){ value=(value<<8)|b; bits+=8; while(bits>=5){bits-=5;out+=ENCODING[(value>>bits)&31]; value&=(1<<bits)-1;}}
  while(out.length<26) out+=ENCODING[Math.floor(Math.random()*32)]; return out.slice(0,26);
}
export function sha256(text:string): string {
  const bytes=new TextEncoder().encode(text),bitLen=bytes.length*8,withOne=bytes.length+1,paddedLen=Math.ceil((withOne+8)/64)*64,data=new Uint8Array(paddedLen);data.set(bytes);data[bytes.length]=0x80;
  const dv=new DataView(data.buffer);dv.setUint32(paddedLen-8,Math.floor(bitLen/0x100000000));dv.setUint32(paddedLen-4,bitLen>>>0);
  const K=[0x428a2f98,0x71374491,0xb5c0fbcf,0xe9b5dba5,0x3956c25b,0x59f111f1,0x923f82a4,0xab1c5ed5,0xd807aa98,0x12835b01,0x243185be,0x550c7dc3,0x72be5d74,0x80deb1fe,0x9bdc06a7,0xc19bf174,0xe49b69c1,0xefbe4786,0x0fc19dc6,0x240ca1cc,0x2de92c6f,0x4a7484aa,0x5cb0a9dc,0x76f988da,0x983e5152,0xa831c66d,0xb00327c8,0xbf597fc7,0xc6e00bf3,0xd5a79147,0x06ca6351,0x14292967,0x27b70a85,0x2e1b2138,0x4d2c6dfc,0x53380d13,0x650a7354,0x766a0abb,0x81c2c92e,0x92722c85,0xa2bfe8a1,0xa81a664b,0xc24b8b70,0xc76c51a3,0xd192e819,0xd6990624,0xf40e3585,0x106aa070,0x19a4c116,0x1e376c08,0x2748774c,0x34b0bcb5,0x391c0cb3,0x4ed8aa4a,0x5b9cca4f,0x682e6ff3,0x748f82ee,0x78a5636f,0x84c87814,0x8cc70208,0x90befffa,0xa4506ceb,0xbef9a3f7,0xc67178f2];
  let h0=0x6a09e667,h1=0xbb67ae85,h2=0x3c6ef372,h3=0xa54ff53a,h4=0x510e527f,h5=0x9b05688c,h6=0x1f83d9ab,h7=0x5be0cd19;const w=new Uint32Array(64),rotr=(x:number,n:number)=>(x>>>n)|(x<<(32-n));
  for(let off=0;off<data.length;off+=64){for(let i=0;i<16;i++)w[i]=dv.getUint32(off+i*4);for(let i=16;i<64;i++){const s0=rotr(w[i-15],7)^rotr(w[i-15],18)^(w[i-15]>>>3),s1=rotr(w[i-2],17)^rotr(w[i-2],19)^(w[i-2]>>>10);w[i]=(w[i-16]+s0+w[i-7]+s1)>>>0;}let a=h0,b=h1,c=h2,d=h3,e=h4,f=h5,g=h6,h=h7;for(let i=0;i<64;i++){const S1=rotr(e,6)^rotr(e,11)^rotr(e,25),ch=(e&f)^(~e&g),t1=(h+S1+ch+K[i]+w[i])>>>0,S0=rotr(a,2)^rotr(a,13)^rotr(a,22),maj=(a&b)^(a&c)^(b&c),t2=(S0+maj)>>>0;h=g;g=f;f=e;e=(d+t1)>>>0;d=c;c=b;b=a;a=(t1+t2)>>>0;}h0=(h0+a)>>>0;h1=(h1+b)>>>0;h2=(h2+c)>>>0;h3=(h3+d)>>>0;h4=(h4+e)>>>0;h5=(h5+f)>>>0;h6=(h6+g)>>>0;h7=(h7+h)>>>0;}return[h0,h1,h2,h3,h4,h5,h6,h7].map(x=>x.toString(16).padStart(8,"0")).join("");
}
function globRegex(glob:string):RegExp{const g=glob.replace(/\\/g,"/");let out="";const esc=(c:string)=>/[.+^${}()|[\]\\]/.test(c)?`\\${c}`:c;for(let i=0;i<g.length;i++){if(g[i]==="*"&&g[i+1]==="*"&&g[i+2]==="/"){out+="(?:.*/)?";i+=2;continue;}if(g[i]==="*"&&g[i+1]==="*"){out+=".*";i++;continue;}if(g[i]==="*"){out+="[^/]*";continue;}if(g[i]==="?"){out+="[^/]";continue;}out+=esc(g[i]);}return new RegExp(`^${out}$`);}
function matches(path:string,patterns:string[]):boolean{return patterns.some(p=>globRegex(p).test(path));}
export function selectSlicePaths(def:SliceDefinitionV1,allPaths:string[]):string[]{const included=allPaths.map(normalizeBrainSharePath).filter(p=>matches(p,def.include)),excluded=def.exclude??[];return[...new Set(included.filter(p=>!matches(p,excluded)))].sort();}
export function ensureManifestIdentities(manifest:ProjectManifestV1,files:Record<string,string>):ProjectManifestV1{const notes={...manifest.notes};for(const[raw,content]of Object.entries(files)){const path=normalizeBrainSharePath(raw),hash=sha256(content);if(notes[path]){notes[path]={...notes[path],hash,updatedAt:new Date().toISOString()};continue;}const renamed=Object.entries(notes).find(([old,n])=>!Object.prototype.hasOwnProperty.call(files,old)&&n.hash===hash);if(renamed){const[old,n]=renamed;delete notes[old];notes[path]={...n,hash,updatedAt:new Date().toISOString()};}else notes[path]={id:createUlid(),hash,updatedAt:new Date().toISOString()};}return{...manifest,notes};}
function dirnamePosix(p:string){const i=p.lastIndexOf("/");return i<0?"":p.slice(0,i)}
function normalizeJoined(base:string,target:string){const parts=`${base}/${target}`.split("/"),out:string[]=[];for(const p of parts){if(!p||p===".")continue;if(p==="..")out.pop();else out.push(p)}return out.join("/")}
function resolveTarget(sourcePath:string,target:string,paths:string[],titles:Map<string,string>):string|undefined{const clean=target.replace(/\\/g,"/").replace(/\.md$/i,"");if(target.includes("/")||target.startsWith(".")){const base=normalizeJoined(dirnamePosix(sourcePath),target),candidates=[base,`${base}.md`];return candidates.find(c=>paths.includes(c));}const lower=clean.toLowerCase();return paths.find(p=>p.replace(/\.md$/i,"").split("/").pop()?.toLowerCase()===lower)??[...titles].find(([,t])=>t.toLowerCase()===lower)?.[0];}
export function compileSlice(manifest:ProjectManifestV1,def:SliceDefinitionV1,files:Record<string,string>,createdAt=new Date().toISOString()):CompiledSliceV1{assertSliceId(def.id);const all=Object.keys(files).map(normalizeBrainSharePath),selected=selectSlicePaths(def,all);if(!selected.length)throw new Error(`Slice ${def.id} matched no files`);const docs=new Map(selected.map(p=>[p,parseMarkdown(files[p],p.split("/").pop()?.replace(/\.md$/i,"")||p)])),titles=new Map([...docs].map(([p,d])=>[p,d.title])),edges:SliceEdgeV1[]=[];for(const[path,doc]of docs){const from=manifest.notes[path]?.id;if(!from)throw new Error(`Missing stable identity for ${path}`);for(const link of doc.links){const targetPath=resolveTarget(path,link.target,selected,titles);if(!targetPath)continue;const to=manifest.notes[targetPath]?.id;if(to)edges.push({from,to,kind:link.kind});}}const backlinks:Record<string,string[]>={};for(const e of edges)(backlinks[e.to]??=[]).push(e.from);for(const k of Object.keys(backlinks))backlinks[k]=[...new Set(backlinks[k])].sort();const sliceFiles=selected.map(path=>({id:manifest.notes[path]!.id,path,hash:sha256(files[path]),title:docs.get(path)!.title})),revisionSeed=JSON.stringify({id:def.id,files:sliceFiles.map(f=>[f.id,f.hash]),edges}),revision=sha256(revisionSeed).slice(0,24);return{protocol:1,id:def.id,revision,title:def.title,description:def.description??"",visibility:def.visibility??"unlisted",live:def.live!==false,entrypoint:def.entrypoint,createdAt,files:sliceFiles,edges,backlinks};}
export interface SliceDiff{added:string[];removed:string[];changed:string[];edgeChanges:number}
export function diffSlices(before:CompiledSliceV1,after:CompiledSliceV1):SliceDiff{const b=new Map(before.files.map(f=>[f.id,f])),a=new Map(after.files.map(f=>[f.id,f])),added=[...a.keys()].filter(k=>!b.has(k)),removed=[...b.keys()].filter(k=>!a.has(k)),changed=[...a.keys()].filter(k=>b.has(k)&&a.get(k)!.hash!==b.get(k)!.hash),ek=(e:SliceEdgeV1)=>`${e.from}>${e.to}:${e.kind}`,bs=new Set(before.edges.map(ek)),as=new Set(after.edges.map(ek)),edgeChanges=[...bs].filter(x=>!as.has(x)).length+[...as].filter(x=>!bs.has(x)).length;return{added,removed,changed,edgeChanges};}
